name: Publish Tar
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'latest'

jobs:
  publish-tar:
    permissions: write-all
    name: Publish tar as release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive
        run: tar -cf archive.tar ./*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: archive.tar
          tag_name: ${{ github.event.inputs.version }}
          name:  Release for Zen - ${{ github.event.inputs.version }}
          body: |
            ### Release ${{ github.event.inputs.version }}
            - sha: ${{ github.sha }}
