name: Publish Tar
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'latest'

jobs:
  publish-tar:
    permissions: write-all
    name: Publish tar as release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive
        run: tar -cf archive.tar ./*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }} (${{ github.sha }})
          body: |
            Changes in this Release
          draft: false
          prerelease: false
